spring:
  # ??????????? ??????? ?????? ?? ????? .env
  config:
    import: optional:file:.env[.properties]
  # ???????????? ??????????? ? ???? ??????
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # ???????????? liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: bank_api
security:
  # Конфигурация Jwt токенов (секретный ключ, время жизни короткоживущего и долгоживущего токенов)
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30